BlogApp/BlogApp/Models/Post.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace BlogApp.Models
{
    public class Post
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Body { get; set; }
        public DateTime CreatedDate { get; set; } = DateTime.Now;
    }
}

BlogApp/BlogApp/ViewModels/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace BlogApp.ViewModels
{
    public class LoginViewModel
    {
        public string UserName { get; set; }
        public string Password { get; set; }
    }
}

BlogApp/BlogApp/Controllers/AuthController.cs
using BlogApp.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace BlogApp.Controllers
{
    public class AuthController : Controller
    {
        private SignInManager<IdentityUser> _signInManager;

        public AuthController(SignInManager<IdentityUser> signInManager)
        {
            _signInManager = signInManager;
        }

        [HttpGet]
        public IActionResult Login()
        {
            return View(new LoginViewModel());
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginViewModel vm)
        {
            var result = await _signInManager.PasswordSignInAsync(vm.UserName, vm.Password, false, false);

            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public async Task<IActionResult> Logout()
        {
            await _signInManager.SignOutAsync();

            return RedirectToAction("Index", "Home");
        }
    }
}

BlogApp/BlogApp/Controllers/HomeController.cs
using BlogApp.Data;
using BlogApp.Data.Repository;
using BlogApp.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace BlogApp.Controllers
{
    public class HomeController : Controller
    {
        private IRepository _repository;

        public HomeController(IRepository repository)
        {
            _repository = repository;
        }

        public IActionResult Index()
        {
            var posts = _repository.GetAllPosts();

            return View(posts);
        }
        public IActionResult Post(int id)
        {
            var post = _repository.GetPost(id);

            return View(post);
        }
    }
}

BlogApp/BlogApp/Controllers/PanelController.cs
using BlogApp.Data.Repository;
using BlogApp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace BlogApp.Controllers
{
    [Authorize(Roles = "Admin")]
    public class PanelController : Controller
    {
        private IRepository _repository;

        public PanelController(IRepository repository)
        {
            _repository = repository;
        }

        public IActionResult Index()
        {
            var posts = _repository.GetAllPosts();

            return View(posts);
        }

        [HttpGet]
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return View(new Post());
            }
            else
            {
                var post = _repository.GetPost((int)id);

                return View(post);
            }
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Post post)
        {
            if (post.Id > 0)
            {
                _repository.UpdatePost(post);
            }
            else
            {
                _repository.AddPost(post);
            }

            if (await _repository.SaveChangesAsync())
            {
                return RedirectToAction("Index");
            }
            else
            {
                return View(post);
            }

        }

        [HttpGet]
        public async Task<IActionResult> Remove(int id)
        {
            _repository.RemovePost(id);
            await _repository.SaveChangesAsync();

            return RedirectToAction("Index");
        }
    }
}

BlogApp/BlogApp/Views/Home/Edit.cshtml
@model Post

@{

}

<div>
    <form asp-controller="Home" asp-action="Edit" method="post">
        <div>
            <label>Title</label>
            <input asp-for="Title" />
        </div>
        <div>
            <label>Body</label>
            <input asp-for="Body" />
        </div>
        <div>
            <input type="submit" value="Submit" />
        </div>
    </form>
</div>

BlogApp/BlogApp/Views/Home/Index.cshtml
@model IEnumerable<Post>

@{

}
<h2>Home Page</h2>

<div>
    <ul>
        @foreach (var post in Model)
        {
            <li>
                <a asp-controller="Home" asp-action="Post" asp-route-id="@post.Id">
                    @post.Title
                </a>
            </li>
        }
    </ul>
</div>

BlogApp/BlogApp/Views/Home/Post.cshtml
@model Post

@{ 

}
<h2>@Model.Title</h2>

<p>@Model.Body</p>

BlogApp/BlogApp/Views/Panel/Edit.cshtml
@model Post

@{

}

<div>
    <form asp-controller="Panel" asp-action="Edit" method="post">
        <div>
            <label>Title</label>
            <input asp-for="Title" />
        </div>
        <div>
            <label>Body</label>
            <input asp-for="Body" />
        </div>
        <div>
            <input type="submit" value="Submit" />
        </div>
    </form>
</div>

BlogApp/BlogApp/Views/Panel/Index.cshtml
@model IEnumerable<Post>

@{

}
<h2>Admin Panel</h2>

<div>
    <ul>
        @foreach (var post in Model)
        {
            <li>
                @post.Title
                -
                <a asp-controller="Panel" asp-action="Edit" asp-route-id="@post.Id">
                    Edit
                </a>
                -
                <a asp-controller="Panel" asp-action="Remove" asp-route-id="@post.Id">
                    Remove
                </a>
            </li>
        }
    </ul>
</div>

BlogApp/BlogApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div>
        <a asp-controller="Home" asp-action="Index">Home</a>
        <a asp-controller="Panel" asp-action="Edit">Create Post</a>
        <a asp-controller="Panel" asp-action="Index">Admin Panel</a>

        @if (User.Identity.IsAuthenticated)
        {
            <a asp-controller="Auth" asp-action="Logout">Logout</a>
        }
        else
        {
            <a asp-controller="Auth" asp-action="Login">Sign In</a>
        }


    </div>
    <div>
        @RenderBody()
    </div>
</body>
</html>